all: 1 2 3

1: 1.c templateFiles.c
	gcc -Wall -Wextra -o 1 1.c templateFiles.c

2: 2.c templateFiles.c
	gcc -Wall -Wextra -o 2 2.c templateFiles.c

3: 3.c templateFiles.c
	gcc -Wall -Wextra -o 3 3.c templateFiles.c

clean:
	rm -f 1 2 3